site_name: ""
copyright: Copyright &copy; KurrawongAI, 2025
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
theme:
  name: material
  favicon: assets/favicon-32x32.png
  palette:
    scheme: kai
  logo: assets/KurrawongAI-inverted.svg
  features:
    - navigation.indexes
    - toc.follow
  # custom_dir: overrides
nav:
    - 'index.md'
    - 'Prez':
        - 'prez/index.md'
        - 'UI': 'prez/ui.md'
        - 'Manifest': 'prez/manifest.md'
        - 'Data Preparation': 'prez/data-preparation.md'
        - 'Deploying':
            - 'AWS': 'prez/deploying/aws.md'
            - 'Azure':
              - 'App Service': 'prez/deploying/azure/appservice.md'
              - 'Container': 'prez/deploying/azure/container.md'
        - 'Developers': 'prez/developers.md'
    - 'KAI Tools':
        - 'tools/index.md'
        - 'Kurra': 'tools/kurra.md'
        - 'Labelify': 'tools/labelify.md'
        - 'OGC Tests': 'tools/ogc-tests.md'
        - 'Prefix Lookup': 'tools/prefix-lookup.md'
        - 'ProvWorkflow': 'tools/provworkflow.md'
        - 'pyLODE': 'tools/pylode.md'
        - 'RDF Converter': 'tools/rdf-converter.md'
        - 'RDF Merger': 'tools/rdf-merger.md'
        - 'SHACL Validator': 'tools/shacl-validator.md'
        - 'SPARQL Parser': 'tools/sparql-parser.md'
        - 'VocEdit': 'tools/vocedit.md'
        - 'VocExcel': 'tools/vocexcel.md'
    - '3rd Party Products':
        - 'Fuseki': '3rdparty/fuseki.md'

# SVG resizer: https://svg-converter.com/resize