site_name: ""
copyright: Copyright &copy; KurrawongAI, 2025
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      toc_depth: "3"
theme:
  name: material
  favicon: assets/favicon-32x32.png
  palette:
    scheme: kai
  logo: assets/KurrawongAI-inverted.svg
  features:
    - navigation.indexes
    # - navigation.expand
    - toc.follow
  # custom_dir: overrides
nav:
    - 'index.md'
    - Products:
        - 'Prez':
            - 'products/prez/index.md'
            - 'UI': 'products/prez/ui.md'
            - 'Manifest': 'products/prez/manifest.md'
            - 'Data Preparation': 'products/prez/data-preparation.md'
            - 'Deploying':
                - 'AWS': 'products/prez/deploying/aws.md'
                - 'Azure':
                  - 'App Service Deployment': 'products/prez/deploying/azure/appservice.md'
            - 'Developers': 'products/prez/developers.md'
        - 'Olis': 'products/olis.md'
        - 'KAI Tools':
            - 'products/tools/index.md'
            - 'Kurra': 'products/tools/kurra.md'
            - 'Labelify': 'products/tools/labelify.md'
            - 'OGC Tests': 'products/tools/ogc-tests.md'
            - 'Prefix Lookup': 'products/tools/prefix-lookup.md'
            - 'Prez Manifest': 'products/tools/prezmanifest.md'
            - 'ProvWorkflow': 'products/tools/provworkflow.md'
            - 'pyLODE': 'products/tools/pylode.md'
            - 'RDF Converter': 'products/tools/rdf-converter.md'
            - 'RDF Merger': 'products/tools/rdf-merger.md'
            - 'SHACL Validator': 'products/tools/shacl-validator.md'
            - 'SPARQL Parser': 'products/tools/sparql-parser.md'
            - 'VocEdit': 'products/tools/vocedit.md'
            - 'VocExcel': 'products/tools/vocexcel.md'
        - '3rd Party':
            - 'Fuseki': 'products/3rdparty/fuseki.md'
    - Concepts:
        - 'Vocabs':
            - 'Introduction': 'concepts/vocabs/introduction.md'
            - 'Advanced': 'concepts/vocabs/creation.md'
            - 'Patterns': 'concepts/vocabs/patterns.md'

# SVG resizer: https://svg-converter.com/resize

